package com.example

class Example {
    fun checkFoo() {
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
    }
}
