package com.example

class Example {
    /**
     * This method signature is in the detekt baseline, so it doesn't
     * cause a failure. But if you remove this comment and run detekt again,
     * it fails.
     */
    fun checkFoo() {
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
        println("This method is way too long")
    }
}
